name: nostr_client
description: Nostr client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
