name: models
description: A package containing data models used across the application.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  equatable: ^2.0.5
  hive_ce: ^2.10.1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.16.0
  nostr_sdk:
    path: ../nostr_sdk

dev_dependencies:
  build_runner: ^2.7.1
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
